services:
  root-back:
    container_name: root-back
    build: ./backend
    networks:
      - app-network
      - db-network
    ports:
      - "8000:8000"
    # env_file:
    #   - .env
    volumes:
      - ./back:/backend

  root-front:
    container_name: root-front
    build: 
      context: ./frontend
      target: builder
    volumes:
      - front_dist:/app/build
    
  # redis는 추후 사용

  # root-redis:
  #   container_name: root-redis
  #   image: redis:7-alpine
  #   networks:
  #     - db-network
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   env_file:
  #     - .env
  #   command: >
  #     redis-server
  #     --requirepass ${REDIS_ROOT_PASSWORD}
  #     --appendonly yes
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "-a", "${REDIS_ROOT_PASSWORD}", "ping"]
  #     interval: 30s
  #     timeout: 3s
  #     retries: 3
  #     start_period: 10s

  root-nginx:
    container_name: root-nginx
    image: nginx:latest
    networks:
      - db-network
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - front_dist:/usr/share/nginx/html
    depends_on:
      - root-front
      - root-back
    ports:
      - "80:80"

volumes:
  redis_data:
  front_dist:


networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge